name: Notify on Pipeline Completion
description: Sends Telegram notifications on workflow completion

inputs:
  step_checkout_status:
    description: "Status of the checkout step"
    required: true
  step_clone_repo_status:
    description: "Status of the clone repository step"
    required: true
  telegram_chat_ids:
    description: "Telegram chat IDs"
    required: true
  telegram_bot_token:
    description: "Telegram bot token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Job Status
      shell: bash
      run: |
        if [[ "${{ github.event.conclusion }}" == "success" ]]; then
          echo "SUCCESS" > status.txt
        else
          echo "FAILURE" > status.txt
        fi

    - name: Send Telegram Notification
      shell: bash
      run: |
        STATUS=$(cat status.txt)
        if [[ "$STATUS" == "SUCCESS" ]]; then
          MESSAGE="🎉 *Build Succeeded* \n*Stage*: Deployed backend application to EC2 \n*Status*: Success"
        else
          ERROR_MESSAGE=$(tail -n 100 $GITHUB_WORKSPACE/error.log || echo "No error log available")
          MESSAGE="🚨 *Build Failed* \n*Stage*: Deploy Backend \n*Status*: Failure \n*Error*: \n\`\`\`$ERROR_MESSAGE\`\`\`"
        fi

        IFS=',' read -ra CHAT_IDS <<< "${{ inputs.telegram_chat_ids }}"
        for CHAT_ID in "${CHAT_IDS[@]}"; do
          curl -s --data "chat_id=$CHAT_ID" \
          --data-urlencode "text=$MESSAGE" \
          --data "parse_mode=Markdown" \
          --data "disable_web_page_preview=true" \
          https://api.telegram.org/bot${{ inputs.telegram_bot_token }}/sendMessage
        done
